name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install essential packages
        run: sudo apt update && sudo apt install -y cmake g++ git

      - name: Build the configuration
        run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake ..
          rm -rf libssh2-build
          cmake -S _deps/libssh2-src -B _deps/libssh2-build -DBUILD_SHARED_LIBS=OFF
          cmake --build _deps/libssh2-build

      - name: Compile
        run: |
          cd build
          make
